// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VUartKaraReg__Trace.cpp"
#include "VUartKaraReg__Trace__1.cpp"
#include "VUartKaraReg__Syms.cpp"
#include "VUartKaraReg__Trace__Slow.cpp"
