// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VUartKaraReg.cpp"
#include "VUartKaraReg__1.cpp"
#include "VUartKaraReg__Slow.cpp"
#include "VUartKaraReg__1__Slow.cpp"
